### ISSUE TITLE
Failed to create VM using 420.sh

### ISSUE THREAD

**Issue by ix-56h** [thdelmas/Bistro42#1]
Hi there,

I'm running the script on MacOS X Mojave 10.14.6 and i got this error : 

`
➜  Bistro42 git:(main) ./420.sh xun
	🍻 Bistro42 🍻
Welcome niguinti
Please choose your base distribution
 1) AlmaLinux 8.3	       36) Lubuntu 20.10
 2) Android-x86		       37) Lubuntu 21.04
 3) Arch Linux		       38) MX Linux 19
 4) Arch Linux 2021.01.01      39) Mageia 7.1
 5) ArcoLinux 20.11	       40) Manjaro 19
 6) Artix Linux 20210101       41) Manjaro 20.2
 7) CentOS 6		       42) Manjaro 21.0
 8) CentOS 7		       43) PCLinuxOS 2020.10
 9) CentOS 8		       44) Parrot OS Security 4.10
10) Debian 10		       45) Peppermint 10
11) Debian 9		       46) Pop!_OS 20.04
12) Deepin 15.11	       47) Pop!_OS 20.10
13) Deepin 20.1 (1010)	       48) PureOS 9.0
14) Devuan 3.1.0	       49) Q4OS 3.13
15) EndeavourOS		       50) Rocky Linux 8.3 [RC]
16) EndeavourOS 2021.02.03     51) Solus 4.1
17) Endless OS 3.9.0	       52) Solus 4.2
18) Fedora 31		       53) Ubuntu 16.04
19) Fedora 32		       54) Ubuntu 18.04
20) Fedora 33		       55) Ubuntu 19.10
21) Fedora 34 Beta	       56) Ubuntu 20.04
22) Feren OS 2021.01	       57) Ubuntu 20.10
23) Garuda Linux 201205	       58) Ubuntu 21.04
24) GeckoLinux 152.210223      59) Ubuntu Kylin 20.04
25) KDE neon		       60) Ubuntu Kylin 20.10
26) KaOS 2021.01	       61) Ubuntu MATE 18.04.5
27) Kali Linux 2020.4	       62) Ubuntu MATE 20.04.2
28) Kali Linux 2021.1	       63) Ubuntu MATE 20.10
29) Kubuntu 20.04	       64) Ubuntu MATE 21.04
30) Kubuntu 20.10	       65) Ubuntu Studio 20.04 [LTS]
31) Kubuntu 21.04	       66) Xubuntu 20.04.1
32) Linux Mint 19	       67) Zorin OS 15.3
33) Linux Mint 20	       68) antiX 19
34) Lubuntu 18.04	       69) elementary OS 5.1
35) Lubuntu 20.04	       70) openSUSE 15.2
#? 66
Your selection: Xubuntu 20.04.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28669  100 28669    0     0  1062k      0 --:--:-- --:--:-- --:--:-- 1076k
mkdir: .build: File exists
Downloading OS image
https://techloudgeek.com/download/image/?link=https://dl531.linuxvmimages.com/VirtualBox/X/Xubuntu_20.04.1_VB.zip
######################################################################## 100.0%
https://dl531.linuxvmimages.com/VirtualBox/X/Xubuntu_20.04.1_VB.zip
######################################################################## 100.0%
Xubuntu_20.04.1_VB.zip
zip
Xubuntu_20
Archive:  Xubuntu_20.04.1_VB.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Xubuntu_20.04.1_VB.zip or
        Xubuntu_20.04.1_VB.zip.zip, and cannot find Xubuntu_20.04.1_VB.zip.ZIP, period.
Import ova...
Oracle VM VirtualBox Command Line Management Interface Version 6.1.22
(C) 2005-2021 Oracle Corporation
All rights reserved.

Usage:

VBoxManage import           <ovfname/ovaname>
                            [--dry-run|-n]
                            [--options keepallmacs|keepnatmacs|importtovdi]
                            [--vmname <name>]
                            [--cloud]
                            [--cloudprofile <cloud profile name>]
                            [--cloudinstanceid <instance id>]
                            [--cloudbucket <bucket name>]
                            [more options]
                            (run with -n to have options displayed
                             for a particular OVF. It doesn't work for the Cloud import.)

Syntax error: Not enough arguments for "import" command.
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2727 of file VBoxManageInfo.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 547 of file VBoxManageModifyVM.cpp
VBoxManage: error: Could not find a registered machine named '42OS'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(pszVM).raw(), machine.asOutParam())" at line 722 of file VBoxManageMisc.cpp
Procedding conf for ansible
Requirement already satisfied: ansible==3.3.0 in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: ansible-base<2.11,>=2.10.8 in ./.venv/lib/python3.7/site-packages (from ansible==3.3.0->-r requirements.txt (line 1)) (2.10.10)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.7/site-packages (from ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.7/site-packages (from ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (5.4.1)
Requirement already satisfied: cryptography in ./.venv/lib/python3.7/site-packages (from ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (3.4.7)
Requirement already satisfied: packaging in ./.venv/lib/python3.7/site-packages (from ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (20.9)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.7/site-packages (from jinja2->ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: cffi>=1.12 in ./.venv/lib/python3.7/site-packages (from cryptography->ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (1.14.5)
Requirement already satisfied: pyparsing>=2.0.2 in ./.venv/lib/python3.7/site-packages (from packaging->ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (2.4.7)
Requirement already satisfied: pycparser in ./.venv/lib/python3.7/site-packages (from cffi>=1.12->cryptography->ansible-base<2.11,>=2.10.8->ansible==3.3.0->-r requirements.txt (line 1)) (2.20)
You are using pip version 19.0.3, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ls: /Users/niguinti/.ssh/*.pub: No such file or directory
cat: /Users/niguinti/.ssh/*.pub: No such file or directory
spawn scp -P4222 -pr ansible/roles/common/files/.ssh xubuntu@127.0.0.1:/home/xubuntu/
ssh: connect to host 127.0.0.1 port 4222: Connection refused
lost connection
send: spawn id exp6 not open
    while executing
"send -- "$pass\r""
    (file "./ssh-connect.ex" line 13)
42OS | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 4222: Connection refused",
    "unreachable": true
}

PLAY [all] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [42OS]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 4222: Connection refused", "unreachable": true}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
42OS                       : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
`

**Comment by thdelmas** [comment]
C'est un problème de place dû au 5Giga de la session stud, je vais rajouter un clean du build
